- hosts: localhost

  tasks:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - curl
      - python
      - python-setuptools
      - mcrypt
      - mysql-client
      - mysql-server
      - nginx
      - php5-cli
      - php5-curl
      - php5-intl
      - php5-json
      - php5-fpm
      - php5-mcrypt
      - php5-mysqlnd

  - name: install supervisord
    easy_install: name=supervisor

  - name: setup nginx config
    template: src=/provision/configs/nginx dest=/etc/nginx/sites-available/default force=yes

  - name: diable nginx daemon
    lineinfile: dest=/etc/nginx/nginx.conf line='daemon off;'

  - name: setup php5-fpm config
    template: src=/provision/configs/php.fpm.ini dest=/etc/php5/fpm/php.ini

  - name: setup php5-cli config
    template: src=/provision/configs/php.cli.ini dest=/etc/php5/cli/php.ini

  - name: diable php5-fpm daemon
    lineinfile: dest=/etc/php5/fpm/php-fpm.conf regexp=daemonize* line='daemonize = no'

  - name: enable php5-mcrypt
    shell: php5enmod mcrypt

  - name: setup mysql-server
    template: src=/provision/configs/my.cnf dest=/etc/mysql/my.cnf

  - name: ensure supervisord service directory exists
    file: path=/etc/supervisord/ state=directory mode=0755

  - name: setup supervisord
    template: src=/provision/configs/supervisor.conf dest=/etc/supervisord.conf

  - name: configure supervisord services
    copy: src=/provision/supervisord/ dest=/etc/supervisord/ directory_mode=yes